### ISSUE TITLE
NoSuchElementException when evaluating empty expression

### ISSUE THREAD

**Issue by SlamaFR** [notKamui/Keval#25]
Hi,

When passing an empty string to `eval()`, a `NoSuchElementException` is thrown by Keval.

Here is complete stack trace :
```
Caused by: java.util.NoSuchElementException: List is empty.
    at kotlin.collections.CollectionsKt___CollectionsKt.last(_Collections.kt:386)
    at com.notkamui.keval.ShuntingYardKt.toAbstractSyntaxTree(ShuntingYard.kt:168)
    at com.notkamui.keval.Keval.eval(Keval.kt:120)
```

**Comment by notKamui** [comment]
Thanks, gonna fix this soon<sup>tm</sup>

**Comment by notKamui** [comment]
Fixed it ; Keval now throws a more suitable `KevalInvalidExpressionException`

Closing issue
